### ISSUE TITLE
Support custom social link

### ISSUE THREAD

**Issue by jkroepke** [wkocjan/gatsby-theme-intro#2]
Hi,

there are tons of social networks in the world. Support them all would be result into a huge maintenance. 

It would be great to define some custom social links with color and icon inside social.yaml

**Comment by wkocjan** [comment]
Hi,

Thanks for the proposal! Each social network comes with custom icon, so that's why it's currently a limited list. 

It's however very easy to extend it to additional services - let me know if you want me to add something else to the list.

**Comment by JoelBCarter** [comment]
@wkocjan Could you add [GoodReads](https://www.goodreads.com/) to the list?  I think sharing books read is a really neat way to showcase what you're learning/studying.

**Comment by jkroepke** [comment]
XING would be great: https://www.xing.com/

It's like a local version of linkedin.

**Comment by wkocjan** [comment]
Thanks for suggestions. Just added these both icons (Goodreads and Xing):
https://github.com/wkocjan/gatsby-theme-intro/commit/7241e2ebf518eb8198ade95b2ddd7b51916721d4

The npm package also has been updated to `1.0.6`:
https://www.npmjs.com/package/@wkocjan/gatsby-theme-intro

**Comment by jkroepke** [comment]
Hi @wkocjan,

thanks! I saw that you are using the custom icons from https://react-icons.github.io/

So by default all social site are "supported" if an icon is present at https://react-icons.github.io/icons?name=fa/ .

Coming back to the original question about custom social links. It might be possible without predefine them inside the code?

Remove to translation table `name -> icon` 
https://github.com/wkocjan/gatsby-theme-intro/blob/7241e2ebf518eb8198ade95b2ddd7b51916721d4/gatsby-theme-intro/src/components/social-links/social-icon.js#L17-L28
and add the property `icon` to the social links definition could be one solution like:


```
- name: github
  url: https://github.com/username
  icon: FaGithub

- name: goodreads
  url:
  icon: FaGoodreadsG

- name: xing
  url:
  icon: FaXing

- name: medium
  url:
  icon: FaMedium

- name: whatsapp
  url:
  icon: FaWhatsapp
```
